services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    # restart: unless-stopped
